### ISSUE TITLE
File Descriptor leak - open a SocketChannel but never closed

### ISSUE THREAD

**Issue by schnappi17** [thomsonreuters/Elektron-SDK#78] opened 2018-08-15 03:16 UTC
We try to create a UPA channel. In RsslSocketChannel.java, line 2835, 

`_scktChannel = java.nio.channels.SocketChannel.open();`

A socketChannel was opened. But when we try to close this UPA channel, the  _scktChannel won't be closed, which lead to the file descriptor leak that could be monitored at /proc/${pid}/fd, there are too many link file linked to a Socket[id] file. 

Below is the "too many open files" log from our application:

2018-08-13 08:33:29,987 INFO com.tr.apt.data.access.elektron.upa.SimpleConsumer - Starting connection...
2018-08-13 08:33:29,987 INFO com.tr.apt.data.access.elektron.upa.SimpleConsumer - amer-3.pricing.streaming.edp.thomsonreuters.com
2018-08-13 08:33:29,987 INFO com.tr.apt.data.access.elektron.upa.SimpleConsumer - 14002
2018-08-13 08:33:29,987 INFO com.tr.apt.data.access.elektron.upa.common.ChannelSession - Attempting to connect to server amer-3.pricing.streaming.edp.thomsonreuters.com:14002 ...
2018-08-13 08:33:29,987 ERROR com.tr.apt.data.access.elektron.upa.common.ChannelSession - Connection failure: Too many open files! Will retry shortly.
2018-08-13 08:33:29,987 ERROR com.tr.apt.data.access.elektron.upa.SimpleConsumer - Error initializing channel, will retry: Error
channel: null
ErrorId: -1
sysError: 0
text: Too many open files

**Comment by bberner** [comment] 2018-08-15 20:33
Thank you for your feedback. A JIRA issue has been created and the issue is being investigated. What do you mean "the _scktChannel won't be closed"? RsslSocketChannel close method does call "_scktChannel.close()" but may not if there's an error. Did close return an error code?

**Comment by schnappi17** [comment] 2018-08-17 09:08
This situation happens when we try to connect to a wrong upa host. When connection failed then it will close the channel and try to re-connect. But file descriptors are continuing increasing.

**Comment by bberner** [comment] 2018-08-22 15:29
How quickly does your application close the RsslSocketChannel and reconnect after failing to connect to the wrong host? Every second? 5 second? 10 second?

**Comment by schnappi17** [comment] 2018-08-27 03:33
Every second.

**Comment by vlevendel** [comment] 2018-11-16 16:00
This is been addressed with ESDK1.2.2. Please let us know if there are additional findings. Closing.

**Closed by vlevendel** 2018-11-16 16:00 UTC
