### ISSUE TITLE
ConcurrentModificationException in EMA

### ISSUE THREAD

**Issue by rajkumarboga** [thomsonreuters/Elektron-SDK#34] opened 2017-08-21 04:32 UTC
Hi Dev Team,

As per TREP team suggestion from https://community.developers.thomsonreuters.com/questions/17574/view.html. Posting my query directly to Dev Team. Please help.
We recently migrated our code using TREP EMA API using jdk 1.8. After that we faced 2 times below ConcurrentModificationException error in PROD env and hence our process terminated. Then we had to start our service again. Kindly help to fix this issue ASAP.

We made the connection to TREP using DACSID provided by MDS team and reference code EMA Consumer - Requesting and displaying MarketPrice data shared by Umer Nalla/Team.

java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.remove(HashMap.java:1451)
at com.thomsonreuters.ema.access.OmmBaseImpl.rsslReactorDispatchLoop(OmmBaseImpl.java:985)
at com.thomsonreuters.ema.access.OmmBaseImpl.uninitialize(OmmBaseImpl.java:258)
at com.thomsonreuters.ema.access.OmmConsumerImpl.uninitialize(OmmConsumerImpl.java:46)
at com.d3k.reuters.DealLocator.startDealService(DealLocator.java:193)
at com.d3k.reuters.DealLocator.<init>(DealLocator.java:75)
at com.d3k.reuters.ReutersStartup.startService(ReutersStartup.java:66)
at com.d3k.reuters.ReutersStartup.main(ReutersStartup.java:81)

Please let me know for any details required.
Thanks. Raj

**Comment by rajkumarboga** [comment] 2017-11-03 09:59
Dear Dev Team,
May I followup on this. Thanks. Raj

**Comment by seba5** [comment] 2017-11-03 15:16
Hi Raj,

what version of EMA are you using? What is you application doing? Are you using the user dispatch or API dispatch mode? I see that the OmmConsumerImpl.uninitialize() method was called, is the application exiting when this is happening? Thanks.

**Comment by frajt** [comment] 2017-11-03 16:34
Hi seba5,

He is obviously using the 1.0.7 version which contains the rsslReactorDispatchLoop method call at the line 258. What is a bit strange that the DealLocator calls the uninitialize from the startDealService method.

I look at the latest OmmBaseImpl implementation and its full of synchronization defects exactly around the dispatch thread handling. The uninitialize method has still contention with the running rsslReactorDispatchLoop thread as setting the volatile _threadRunning to false and reading byte from the pipe (btw. I think you wanted to call pipeWrite and not pipeRead, master line 284)  will not make the rsslReactorDispatchLoop break the selection key removal loop. The rsslReactorDispatchLoop is still running while you are calling it again from the uninitialize method invocation thread. Very simple.

Btw. your strange concept of synchronization between the dispatch loop and the other thread (timeout handling) using the Pipe socket channel only shows that you have no understanding how the NIO works. To wakeup the Selector you simply call the selecter.wakeup() method, there is no need to have synthetically created channel on which you simulate traffic to force the select method to return. 

Btw. _pipeWriteCount is not using any memory barrier which is required when accessed from multiple threads, you should use AtomicInteger or if you want to be cool then Unsafe CAS will do all in one instruction. Anyway the read/write _pipeWriteCount conditions are somehow strange not guaranteeing what you want them to do for you in the case of the uninitialize method trying to wait for dispatcher thread finishing. 

Btw. the correct usage of the Lock 
lock.lock();
try {
 my business
} finally {
 lock.unlock();
}
with your usages you are asking for keeping the lock locked if exception is thrown in "my business" part

Btw. using ExecutorService for running the API_DISPATCH thread is just an extra complication, simple Thread and smart protections around rsslReactorDispatchLoop method will allow you handle the API_DISPATCH and USER_DISPATCH operation model consistently including the termination required in the uninitialize method.

Btw. calling rsslReactorDispatchLoop from the handleLoginReqTimeout you are asking for same troubles

Btw. ...

Regards,
Michal

**Comment by rajkumarboga** [comment] 2017-11-06 10:11
Hi Seba,
We are using this one Elektron-SDK1.0.8.java.
We have done migration from old legacy connection to D3000(D3K) system with EMA TREP API.
About our Application: It is a stand alone program , it connects D3000 system to get deals information for dealing codes of RTNN, SCSG. 

We are using API dispatch only. We creating connection by just followed the in EMA examples shared at
Elektron-SDK1.0.8.java\Ema\Src\examples\java\com\thomsonreuters\ema\examples\training\consumer\series100\example100__MarketPrice__Streaming/Consumer.java
This is ConcurrentModificationException is coming once in a week in PRD and we had to restart our program as temp fix.
Kindly help to give permanent fix. Thanks.

**Comment by seba5** [comment] 2017-11-06 19:18
Hi Raj,
would it be possible for you to retest it with the newest release of the ESDK? The latest release is ESDK-1.1.1. 
Thanks you.

**Comment by rajkumarboga** [comment] 2017-11-07 05:51
Hi Saba / Michal,
I am not sure on we can test this with new release of ESDK because its happening only in PRD.
Below is the way we currently connecting to TREP. Is there anything wrong in this? or Is there any other way to connect?
Kindly check and advice. 

`public static void main(String[] args)
	{
		OmmConsumer testConsumer = null;
		try
		{
			Consumer testAppClient = new Consumer();
			
			OmmConsumerConfig config = EmaFactory.createOmmConsumerConfig();
			
			testConsumer  = EmaFactory.createOmmConsumer(config.host("<IP & PORT>").username("<DACS_ID>"));
			
			ReqMsg reqMsg = EmaFactory.createReqMsg();
			
			<LOOP>
			testConsumer.registerClient(reqMsg.serviceName("<SERVICE_NAME>").name("<DEALINDCODE1>#INFO"), testAppClient);
			/*
			We are checking whether we received response from our request. 
			If not we will keep thread to sleep for for 10 micro seconds and check again.
			This process will continue till we get response for our request.
			*/

			testConsumer.registerClient(reqMsg.serviceName("<SERVICE_NAME>").name("<DEALINDCODE2>#INFO"), testAppClient);		
			/*
			We are checking whether we received response from our request. 
			If not we will keep thread to sleep for for 10 micro seconds and check again.
			This process will continue till we get response for our request.
			*/
			
			testConsumer.registerClient(reqMsg.serviceName("<SERVICE_NAME>").name("<DEALINDCODE3>#INFO"), testAppClient);
			/*
			We are checking whether we received response from our request. 
			If not we will keep thread to sleep for for 10 micro seconds and check again.
			This process will continue till we get response for our request.
			*/
			<END LOOP>

			/*
			Once the responce is received & processed for all services then "finally" will be called 
			to uninitialize the testAppClient channel.
			*/
		} 
		catch (OmmException excp)
		{
			System.out.println(excp.getMessage());
		}
		finally 
		{
			if (testConsumer != null) testConsumer.uninitialize();
			/*
			Here we are getting exception while uninitialize the testConsumer object.
			*/
		}
	}`

**Comment by rajkumarboga** [comment] 2017-11-17 07:24
Hi Saba/Michal,

May I followup on this.

**Comment by seba5** [comment] 2017-11-17 15:56
Hi Raj, this issue has been entered into our internal bug tracking system to get prioritized.

**Comment by frajt** [comment] 2017-11-17 16:10
Hi Raj,

the issue is in the testConsumer.uninitialize() method implementation. If you are unlucky and calling it while there is an update coming, the uninitialize() method will throw back an exception. The only way you can make it somehow working is to try to call several times the uninitialize() method with some short sleep in between:

for(int i = 0; i <= 100; ++i) {
  try {
    testConsumer.uninitialize();
    break;
  } catch(final Throwable t) {
    if(i == 100) {
       // LAST ATTEMPT => RETHROW 
       throw t;
    }
    // WAIT SOME TIME AND TRY AGAIN 
    Thread.sleep(100);
  }
}

I am still very much convinced that the OmmBaseImpl implementation around the dispatch thread handling and user locking is completely crazy. Looking forward to see this addressed but not being very much optimistic as the current code shows there is still a very long path for the Elektron SDK developers to deliver runtime quality at the RFA API level. 

I think I should consider to apply for the Contributor Agreement as fixing the OmmBaseImpl implementation is like 4 hours of work to get it all right. 

Regards,
Michal

**Comment by nipat-kunvutipongsak** [comment] 2017-11-21 03:16
Hello EMA Dev Team,

There is a new recent similar issue [here](https://community.developers.thomsonreuters.com/questions/21232/problem-while-uninitializing-the-ommconsumer.html). Please review whether they have the same root cause or not. If not, the new question will become another EMA Java issue.

Thanks
Nipat K.

**Comment by vlevendel** [comment] 2017-11-21 16:41
Michal, Please make a pull request with your contribution.
Thanks.

**Comment by frajt** [comment] 2017-11-21 17:08
Hi vlevendel,

I hope it will get fixed by Reuters as already 'entered into the internal bug tracking system'. Fixing it my way would require many changes making the implementation pretty away from the Cpp code. Not sure how deep I could go with the changes to be accepted. Not sure what is the Cpp x Java code logic strategy.

Currently I am just taking year-end review of the Elektron SDK progress, trying to understand where it stands, what is the design and run-time benefit compare to the RFA API which I am using since the 2006. 

Let's wait,
Michal

**Comment by frajt** [comment] 2017-11-21 21:05
https://github.com/thomsonreuters/Elektron-SDK/pull/40

**Comment by seba5** [comment] 2017-12-21 21:25
This issue has been fixed with the newest ESDK-1.1.2.G1 release.

**Closed** 2017-12-21 21:48 UTC
