### ISSUE TITLE
Handle leak in OmmBaseImpl.java

### ISSUE THREAD

**Issue by TrLiulu** [thomsonreuters/Elektron-SDK#72] opened 2018-06-28 09:07 UTC
In OmmBaseImpl.java line 185, a NIO pipe is opened :
 _pipe = Pipe.open();
It seems that this pipe's sink and source channel are never closed in uninitialize() method. Two leaked handles on both Linux and Windows can be observed. In our application, the leaking leaded to a "too many open files" error. At the same time, CPU usage was 100% and below log repeated infinitely:

2018-06-27 10:17:59,024 INFO  com.tr.apt.data.access.elektron.ema.AppClient                 - com.tr.apt.data.access.elektron.ema.AppClient@22922bff is stopping
2018-06-27 10:17:59,024 ERROR com.tr.apt.data.access.elektron.ema.AppClient                 - NIP client com.tr.apt.data.access.elektron.ema.AppClient@22922bff is down
2018-06-27 10:17:59,024 INFO  com.tr.apt.data.access.elektron.ema.AppClient                 - Start the NIP session to:
2018-06-27 10:17:59,024 ERROR com.thomsonreuters.ema.access.OmmNiProviderImpl               - loggerMsg
    ClientName: NI_PUB_4816129
    Severity: Error
    Text:    Failed to open Selector: Too many open files
loggerMsgEnd

2018-06-27 10:17:59,024 ERROR com.tr.apt.data.access.elektron.ema.AppClient                 - EMA AppClient Exception:
Exception Type='OmmInvalidUsageException', Text='Failed to open Selector: Too many open files'
        at com.thomsonreuters.ema.access.OmmBaseImpl.ommIUExcept(OmmBaseImpl.java:1219)
        at com.thomsonreuters.ema.access.OmmBaseImpl.initialize(OmmBaseImpl.java:197)
        at com.thomsonreuters.ema.access.OmmNiProviderImpl.<init>(OmmNiProviderImpl.java:205)
        at com.thomsonreuters.ema.access.EmaFactory.createOmmProvider(EmaFactory.java:276)
        at com.tr.apt.data.access.elektron.ema.AppClient.eventLoop(AppClient.java:135)
        at com.tr.apt.data.access.elektron.ema.AppClient.run(AppClient.java:124)
        at java.lang.Thread.run(Thread.java:748)

**Comment by bberner** [comment] 2018-06-28 13:07
Thank you for your feedback. A JIRA issue has been created and the issue is being investigated. We'll let you know if we need further information.

**Comment by bberner** [comment] 2018-08-16 13:32
Fixed with ESDK 1.2.1.L1 release.

**Closed by bberner** 2018-08-16 13:32 UTC
