### ISSUE TITLE
Elektron SDK 1.2.0 rsslNumericStringToReal() regression

### ISSUE THREAD

**Issue by afoster-arcontech** [thomsonreuters/Elektron-SDK#62] opened 2018-05-14 11:57 UTC
I have been running some tests with the Elektron SDK v1.1.1 and v1.2.0 and
identified a difference in the behaviour between the two - very likely a
regression.

The problem occurs while using just the ETA library (aka. librssl.lib) and the
following functions:
rsslRealToString()
rsslNumericStringToReal()

The basis of my test is as follows:
1. Create an RsslReal type and initialise it with a value.
2. Convert the value to a string using rsslRealToString().
3. Convert the string back into a RsslReal using rsslNumericStringToReal().
4. Verify the initial RsslReal value equals the newly converted value.

My input data for the test was:
RsslReal rssl_real;
rssl_real.isBlank = false;
rssl_real.hint = RSSL_RH_EXPONENT7;
rssl_real.value = std::numeric_limits<RsslInt>::max(); // 9223372036854775807

Running this test against Elektron SDK v1.1.1 shows the value to be converted
successfully.

Running this test against Elektron SDK v1.2.0 shows rsslNumericStringToReal()
fails with the error code RSSL_RET_INVALID_DATA.

Could you confirm/explain the difference in behaviour.

**Comment by bberner** [comment] 2018-05-14 16:37
Thank you for your feedback. A JIRA issue has been created and the issue is being investigated. We’ll let you know if we have any problems reproducing the issue.

**Comment by bberner** [comment] 2018-05-31 20:46
Fixed with latest GitHub push with tag Elektron-SDK_1.2.0.2.G1.

**Closed by bberner** 2018-05-31 20:46 UTC
